server {
  listen 4568;
  server_name _;

  location / {
    proxy_pass http://miwayomi:4567;
    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Accept-Encoding "";
    proxy_read_timeout 300s;
    proxy_buffering off;
    sub_filter_types application/vnd.apple.mpegurl application/dash+xml;
    sub_filter "http://miwayomi:4567" "$scheme://$http_host";
    sub_filter_once off;
  }
}
