#!/usr/bin/env bash
set -euo pipefail

new_session_name="$1"
window_to_move="$(tmux display-message -p '#{window_id}')"
placeholder_window="$(tmux new-session -d -P -F '#{window_id}' -s "$new_session_name")"
tmux move-window -s "$window_to_move" -t "$new_session_name:"
tmux kill-window -t "$placeholder_window"
