accent = "#c17013"
cursor = "#f7f6f5"
foreground = "#f7f6f5"
background = "#010102"
selection_foreground = "#010102"
selection_background = "#f7f6f5"

color0 = "#010102"
color1 = "#c17013"
color2 = "#239f7d"
color3 = "#b79319"
color4 = "#5e6fea"
color5 = "#5e6fea"
color6 = "#239f7d"
color7 = "#f7f6f5"
color8 = "#4d4d4d"
color9 = "#ed840b"
color10 = "#14d19e"
color11 = "#e5b40e"
color12 = "#5e6fea"
color13 = "#5e6fea"
color14 = "#14d19e"
color15 = "#fbfafa"
