{
  helpers,
  pkgs,
  lib,
  self,
  ...
}:
let
  inherit (helpers) mkEvalCheck;
  interactiveAgentSkills =
    import
      ../../../../agent-harness/agent-instructions/interactive-skill-catalog/interactive-agent-skills.nix
      {
        hostname = "test";
        inherit pkgs;
      };

  cfg = helpers.homeManagerTestConfiguration [ self.homeManagerModules.codex ];

  codexPackage = cfg.codex.unwrappedPackage;

  fileNames = builtins.attrNames cfg.home.file;

  hasFilePrefix =
    prefix: builtins.any (n: builtins.substring 0 (builtins.stringLength prefix) n == prefix) fileNames;

  dotfilesAgentInstructions = builtins.readFile ../../../../agent-harness/agent-instructions/project-context/dotfiles-agent-instructions.md;
  normalizedDotfilesAgentInstructions = lib.replaceStrings [ "\n" ] [ " " ] dotfilesAgentInstructions;
  codexConfigSeedActivationData = cfg.home.activation.seedCodexConfigAsMutableFile.data or "";
  codexConfigModule = builtins.readFile ../config.nix;
in
{
  codex-bin-wrapper =
    mkEvalCheck "codex-bin-wrapper" (builtins.hasAttr ".local/bin/codex" cfg.home.file)
      ".local/bin/codex should be in home.file";

  codex-package-uses-upstream-binaries =
    assert lib.assertMsg
      (!(codexPackage.drvAttrs ? cargoDeps) && (codexPackage.drvAttrs.patches or [ ]) == [ ])
      "Codex must use unpatched upstream prebuilt binaries; see agent-harness/harnesses/codex/README.md";
    pkgs.runCommand "check-codex-package-uses-upstream-binaries" { } ''
      export HOME="$TMPDIR"
      codexExecutable=${lib.getExe codexPackage}
      codexExecutableDirectory=$(dirname "$(readlink -f "$codexExecutable")")
      test "$codexExecutableDirectory" = "$(dirname "$codexExecutable")"
      test -x "$codexExecutableDirectory/codex-code-mode-host"
      "$codexExecutable" --version >/dev/null 2>&1
      "$codexExecutableDirectory/codex-code-mode-host" --help >/dev/null
      touch "$out"
    '';

  codex-production-plugin-registration =
    mkEvalCheck "codex-production-plugin-registration"
      (
        builtins.hasAttr "installProductionCodexPlugin" cfg.home.activation
        && builtins.hasAttr ".local/share/agent-plugins/dotfiles" cfg.home.file
        && !(hasFilePrefix ".codex/skills/")
      )
      "Codex must register the complete production package without duplicate managed global skill projections";

  codex-global-agents-instructions =
    mkEvalCheck "codex-global-agents-instructions" (builtins.hasAttr ".codex/AGENTS.md" cfg.home.file)
      "core agent rules should be deployed as codex global ~/.codex/AGENTS.md instructions";

  codex-config-nix-source = mkEvalCheck "codex-config-nix-source" (
    builtins.hasAttr ".codex/config.toml.nix-source" cfg.home.file
    && !(builtins.hasAttr ".codex/config.toml" cfg.home.file)
  ) "Codex config must deploy an authoritative nix-source while leaving the live TOML mutable";

  codex-config-uses-alternate-screen =
    mkEvalCheck "codex-config-uses-alternate-screen"
      (lib.hasInfix ''alternate_screen = "always";'' codexConfigModule)
      "Interactive Codex sessions must use the TUI alternate screen instead of terminal scrollback";

  codex-config-leaves-model-runtime-owned =
    mkEvalCheck "codex-config-leaves-model-runtime-owned" (!(lib.hasInfix "model = " codexConfigModule))
      "Codex model selection must remain runtime-owned so a rebuild preserves the user's remembered model";

  codex-config-mutable-seed-activation = mkEvalCheck "codex-config-mutable-seed-activation" (
    builtins.hasAttr "seedCodexConfigAsMutableFile" cfg.home.activation
    && !(builtins.hasAttr "codexBaselineConfig" cfg.home.activation)
    && builtins.elem "linkGeneration" cfg.home.activation.seedCodexConfigAsMutableFile.after
    && lib.hasInfix "CODEX_TRUSTED_PROJECT_PARENT_DIRECTORIES" codexConfigSeedActivationData
    && lib.hasInfix "/home/test/repo" codexConfigSeedActivationData
  ) "Codex config must use Claude-style mutable seeding instead of the legacy generator activation";

  codex-config-legacy-profiles-removed = mkEvalCheck "codex-config-legacy-profiles-removed" (
    !(builtins.hasAttr ".codex/fast.config.toml" cfg.home.file)
    && !(builtins.hasAttr ".codex/deep.config.toml" cfg.home.file)
    && !(builtins.hasAttr ".codex/web.config.toml" cfg.home.file)
  ) "Codex-only generated profiles must stay removed";

  codex-config-agent-instructions-current =
    mkEvalCheck "codex-config-agent-instructions-current"
      (
        !(lib.hasInfix "codex config generator" normalizedDotfilesAgentInstructions)
        && !(lib.hasInfix "regenerated by merging into the existing file" normalizedDotfilesAgentInstructions)
        && lib.hasInfix "agent-harness/harnesses/claude-code/mcps/default.nix" normalizedDotfilesAgentInstructions
        && lib.hasInfix "agent-harness/harnesses/codex/config.nix" normalizedDotfilesAgentInstructions
        && lib.hasInfix "The live model and entries in projects, marketplaces, and plugins survive rebuilds" normalizedDotfilesAgentInstructions
        && lib.hasInfix "declarative source wins every other key collision" normalizedDotfilesAgentInstructions
      )
      "Codex instructions must describe the current authoritative source and mutable seed ownership model";

  codex-retired-plugin-port = mkEvalCheck "codex-retired-plugin-port" (
    !(builtins.hasAttr "codexClaudePluginPort" cfg.home.activation)
  ) "Codex must retain native complete packages without the retired skill-only Claude copier";

}
// import ./hook-registration-checks.nix {
  inherit
    pkgs
    lib
    mkEvalCheck
    cfg
    ;
}
