#!/usr/bin/env bash
set -Eeuo pipefail

readonly CLOSED_WINDOWS_HISTORY_FILE="${XDG_RUNTIME_DIR:-/tmp}/hypr-closed-windows-history"

main() {
	[[ ! -s "$CLOSED_WINDOWS_HISTORY_FILE" ]] && exit 0

	local last_entry launch_command target_workspace_id
	last_entry=$(tail -n 1 "$CLOSED_WINDOWS_HISTORY_FILE")
	launch_command=$(echo "$last_entry" | jq -r '.cmd')
	target_workspace_id=$(echo "$last_entry" | jq -r '.workspace')

	[[ -z "$launch_command" || "$launch_command" == "null" ]] && exit 1

	sed -i '$ d' "$CLOSED_WINDOWS_HISTORY_FILE"

	hyprctl dispatch exec "[workspace $target_workspace_id silent] $launch_command"
}

main
