use ratatui::style::{palette::tailwind, Color};

#[derive(Debug, Default, Clone, Copy)]
pub struct Theme {
    pub button_keyboard_label: Color,
    pub button_label: Color,
    pub debug: Color,
    pub details_border: Color,
    pub details_field_fg: Color,
    pub details_hint_fg: Color,
    pub menu_bg: Color,
    pub menu_button_background: Color,
    pub menu_button_highlight: Color,
    pub menu_button_keyboard_label: Color,
    pub menu_button_label: Color,
    pub menu_button_shadow: Color,
    pub menu_logo_fg: Color,
    pub popup_border: Color,
    pub search_bg: Color,
    pub search_border: Color,
    pub standard_bg: Color,
    pub standard_fg: Color,
    pub status_bar_bg: Color,
    pub status_bar_fg: Color,
    pub table_alt_row: Color,
    pub table_buffer_bg: Color,
    pub table_header_bg: Color,
    pub table_header_fg: Color,
    pub table_normal_row: Color,
    pub table_pattern_highlight_bg: Color,
    pub table_row_fg: Color,
    pub table_selected_cell_style_fg: Color,
    pub table_selected_column_style_fg: Color,
    pub table_selected_row_style_fg: Color,
    pub table_track_bg: Color,
    pub table_track_fg: Color,
}

impl Theme {
    pub fn new() -> Self {
        let palette = &tailwind::CYAN;
        Self {
            button_keyboard_label: Color::White,
            button_label: Color::White,
            debug: tailwind::BLUE.c500,
            details_border: Color::White,
            details_field_fg: Color::White,
            details_hint_fg: Color::White,
            menu_bg: Color::Reset,
            menu_button_background: Color::Reset,
            menu_button_highlight: palette.c800,
            menu_button_keyboard_label: Color::White,
            menu_button_label: Color::White,
            menu_button_shadow: Color::Reset,
            menu_logo_fg: Color::White,
            popup_border: Color::White,
            search_bg: Color::Reset,
            search_border: Color::White,
            standard_bg: Color::Reset,
            standard_fg: Color::White,
            status_bar_bg: Color::Reset,
            status_bar_fg: Color::White,
            table_alt_row: Color::Reset,
            table_buffer_bg: Color::Reset,
            table_header_bg: Color::Reset,
            table_header_fg: Color::White,
            table_normal_row: Color::Reset,
            table_pattern_highlight_bg: palette.c800,
            table_row_fg: Color::White,
            table_selected_cell_style_fg: Color::White,
            table_selected_column_style_fg: Color::White,
            table_selected_row_style_fg: Color::White,
            table_track_bg: Color::Reset,
            table_track_fg: Color::White,
        }
    }
}
