{
  pkgs,
  lib,
  inputs,
  self,
  nixpkgs-version,
  home-version,
}:
let
  helpers = import ../../../../tests/nix-checks/helpers.nix {
    inherit
      pkgs
      lib
      inputs
      nixpkgs-version
      home-version
      ;
  };
  inherit (helpers) mkEvalCheck;

  cfg =
    (inputs.home-manager.lib.homeManagerConfiguration {
      inherit pkgs;
      extraSpecialArgs = {
        hostname = "test";
      };
      modules = [
        self.homeManagerModules.codex
        {
          home = {
            username = "test";
            homeDirectory = "/home/test";
            inherit (helpers) stateVersion;
          };
        }
      ];
    }).config;

  fileNames = builtins.attrNames cfg.home.file;

  hasFilePrefix =
    prefix: builtins.any (n: builtins.substring 0 (builtins.stringLength prefix) n == prefix) fileNames;

  parsedCodexHooksConfig =
    let
      hooksFile = cfg.home.file.".codex/hooks.json" or null;
    in
    if hooksFile != null && hooksFile ? text then
      builtins.fromJSON (builtins.unsafeDiscardStringContext hooksFile.text)
    else
      { };

  dotfilesAgentInstructions = builtins.readFile ../../../../agents/dotfiles.md;
  normalizedDotfilesAgentInstructions = lib.replaceStrings [ "\n" ] [ " " ] dotfilesAgentInstructions;
  codexConfigSeedActivationData = cfg.home.activation.seedCodexConfigAsMutableFile.data or "";

  codexHookEventCommands =
    eventName:
    let
      eventGroups =
        if parsedCodexHooksConfig ? hooks && parsedCodexHooksConfig.hooks ? ${eventName} then
          parsedCodexHooksConfig.hooks.${eventName}
        else
          [ ];
    in
    builtins.concatMap (group: map (hook: hook.command or "") (group.hooks or [ ])) eventGroups;

  codexHookEventRunsScript =
    eventName: scriptName:
    builtins.any (command: lib.hasInfix scriptName command) (codexHookEventCommands eventName);
in
{
  codex-bin-wrapper =
    mkEvalCheck "codex-bin-wrapper" (builtins.hasAttr ".local/bin/codex" cfg.home.file)
      ".local/bin/codex should be in home.file";

  codex-skills-directory =
    mkEvalCheck "codex-skills-directory" (hasFilePrefix ".codex/skills/")
      "skills directory entries should be in home.file";

  codex-skills-only-deploy-complete-skills = mkEvalCheck "codex-skills-only-deploy-complete-skills" (
    !(builtins.hasAttr ".codex/skills/page-composer" cfg.home.file)
  ) "directories without SKILL.md should not be deployed as codex skills";

  codex-research-skill =
    mkEvalCheck "codex-research-skill" (builtins.hasAttr ".codex/skills/research" cfg.home.file)
      "research skill should be deployed for codex";

  codex-core-skill =
    mkEvalCheck "codex-core-skill" (builtins.hasAttr ".codex/skills/core/SKILL.md" cfg.home.file)
      "core skill should be generated for codex";

  codex-global-agents-instructions =
    mkEvalCheck "codex-global-agents-instructions" (builtins.hasAttr ".codex/AGENTS.md" cfg.home.file)
      "core agent rules should be deployed as codex global ~/.codex/AGENTS.md instructions";

  codex-config-nix-source = mkEvalCheck "codex-config-nix-source" (
    builtins.hasAttr ".codex/config.toml.nix-source" cfg.home.file
    && !(builtins.hasAttr ".codex/config.toml" cfg.home.file)
  ) "Codex config must deploy an authoritative nix-source while leaving the live TOML mutable";

  codex-config-mutable-seed-activation = mkEvalCheck "codex-config-mutable-seed-activation" (
    builtins.hasAttr "seedCodexConfigAsMutableFile" cfg.home.activation
    && !(builtins.hasAttr "codexBaselineConfig" cfg.home.activation)
    && builtins.elem "linkGeneration" cfg.home.activation.seedCodexConfigAsMutableFile.after
    && lib.hasInfix "CODEX_TRUSTED_PROJECT_PARENT_DIRECTORIES" codexConfigSeedActivationData
    && lib.hasInfix "/home/test/repo" codexConfigSeedActivationData
  ) "Codex config must use Claude-style mutable seeding instead of the legacy generator activation";

  codex-config-legacy-profiles-removed = mkEvalCheck "codex-config-legacy-profiles-removed" (
    !(builtins.hasAttr ".codex/fast.config.toml" cfg.home.file)
    && !(builtins.hasAttr ".codex/deep.config.toml" cfg.home.file)
    && !(builtins.hasAttr ".codex/web.config.toml" cfg.home.file)
  ) "Codex-only generated profiles must stay removed";

  codex-config-agent-instructions-current =
    mkEvalCheck "codex-config-agent-instructions-current"
      (
        !(lib.hasInfix "codex config generator" normalizedDotfilesAgentInstructions)
        && !(lib.hasInfix "regenerated by merging into the existing file" normalizedDotfilesAgentInstructions)
        && lib.hasInfix "home/base/claude/mcps/default.nix" normalizedDotfilesAgentInstructions
        && lib.hasInfix "home/base/codex/config.nix" normalizedDotfilesAgentInstructions
        && lib.hasInfix "preserving live entries in projects, marketplaces, and plugins" normalizedDotfilesAgentInstructions
        && lib.hasInfix "sourced entries win on key collisions" normalizedDotfilesAgentInstructions
      )
      "Codex instructions must describe the current authoritative source and mutable seed ownership model";

  codex-claude-plugin-port-activation =
    mkEvalCheck "codex-claude-plugin-port-activation"
      (builtins.hasAttr "codexClaudePluginPort" cfg.home.activation)
      "enabled third-party Claude Code plugins should be ported into Codex via an activation step";

  codex-hooks-config-managed-file =
    mkEvalCheck "codex-hooks-config-managed-file" (builtins.hasAttr ".codex/hooks.json" cfg.home.file)
      "Codex hooks should be deployed as a declarative home.file entry";

  codex-hooks-config-current-schema =
    let
      sessionStartGroups =
        if parsedCodexHooksConfig ? hooks && parsedCodexHooksConfig.hooks ? SessionStart then
          parsedCodexHooksConfig.hooks.SessionStart
        else
          [ ];
      firstSessionStartGroup =
        if sessionStartGroups == [ ] then { } else builtins.head sessionStartGroups;
    in
    mkEvalCheck "codex-hooks-config-current-schema" (
      parsedCodexHooksConfig ? hooks && firstSessionStartGroup ? hooks
    ) "Codex hooks.json should use the current top-level hooks schema";

  codex-hooks-config-post-tool-use-auto-format-and-rebuild =
    mkEvalCheck "codex-hooks-config-post-tool-use-auto-format-and-rebuild"
      (
        codexHookEventRunsScript "PostToolUse" "auto-format.py"
        && codexHookEventRunsScript "PostToolUse" "nix-rebuild-trigger.py"
        && codexHookEventRunsScript "PostToolUse" "record-edited-source-file.py"
      )
      "Codex PostToolUse hooks should run auto-format, nix-rebuild-trigger, and record-edited-source-file";

  codex-hooks-config-pre-tool-use-recall-and-guards =
    mkEvalCheck "codex-hooks-config-pre-tool-use-recall-and-guards"
      (
        codexHookEventRunsScript "PreToolUse" "memory-recall.py"
        && codexHookEventRunsScript "PreToolUse" "prohibited-command-guard.py"
        && codexHookEventRunsScript "PreToolUse" "prohibited-words-guard.py"
      )
      "Codex PreToolUse hooks should run memory-recall and the prohibited-command/word guards";

  codex-hooks-config-stop-lint-review =
    mkEvalCheck "codex-hooks-config-stop-lint-review"
      (codexHookEventRunsScript "Stop" "lint-turn-review.py")
      "Codex Stop hook should run lint-turn-review";
}
