[
  "Chudmaxxing"
  "Aura-farming"
  "Redeeming"
  "Clodding"
  "Tokenmaxxing"
  "Slopping"
  "Clanking"
  "Ignoring GPL"
  "Increasing ram prices"
  "Hallucinating"
  "Selling your data"
  "Outsourcing to Mossad"
  "Gemming it up"
  "Absolute coaling"
  "Truth-nuking"
  "Fakecelling"
  "Truecelling"
  "Mogging"
  "Rizzing"
  "Dumbing it down"
  "Enshittifying"
  "Going full retard"
  "Summoning Cheesy Micheal"
  "Degenerating"
  "Running \"sudo rm -rf --no-preserve-root /\""
  "Virtual insanitying"
  "Bomboclating"
  "Gambling"
  "Ending it all"
  "Rebooting"
  "Unicycling"
  "Horsing around"
  "Calling Mahoraga"
  "Calling Kevin"
  "Calling Saul"
  "Nuking SF"
  "Spellcasting"
  "Hexing"
  "Prompt-injecting"
  "Installing Windows"
  "Ultrathinking"
  "Nuking prod"
  "Tokenmining"
  "Questioning"
  "Chinesing"
  "Selling the wife and kids"
  "Increasing shareholder value"
  "Winging it"
  "Cooking"
  "Bitch im workin on it"
  "Hold your horses"
  "Summoning demons"
  "Asking my therapist"
  "Googling it like you should have"
  "Stealing code from Stack Overflow"
  "Pretending to be smart"
  "Having an existential crisis"
  "this is so sad. alexa play despacito"
  "in awe at the size of this file. absolute unit"
  "they don't think it be like it is but it do"
  "i have the power of god and anime on my side"
  "we have code at home. the code at home:"
  "me and the boys at 3am looking for the segfault"
  "it's giving... undefined behavior"
  "no thoughts. head empty. just vibes and pointer arithmetic"
  "sir this is a wendy's. i mean a rust codebase"
  "the compiler and i are in a situationship"
  "live laugh love except the code won't compile so just cry"
  "i showed you my PR please respond"
  "bro really said 'unwrap()' in production and meant it"
  "the code is giving main character energy and not in a good way"
  "every day we stray further from god's design patterns"
  "skill issue (the skill issue is mine)"
  "it compiled. i am not going to question why"
  "oh you're approaching me? i can't refactor your code without getting closer"
  "the function name is a lie. the comments are a lie. everything is a lie"
  "bestie this match statement has 47 arms"
  "caught the bug in 4k"
  "gentlemen, it has been a privilege coding with you tonight"
  "i fear no man. but that regex... it scares me"
  "the audacity of this function to just. sit there. being O(n²)"
  "look at me. i am the maintainer now"
  "you miss 100% of the commits you don't push. - wayne gretzky. - michael scott"
  "to unwrap, or not to unwrap. that is the question. the answer is not to"
  "i'm in this codebase and i don't like it"
  "the call is coming from inside the function"
  "you could not live with your own failure. where did that bring you? back to me"
  "trust the process. the process is panicking"
  "the floor is lava. the lava is your test suite"
  "tell me you write rust without telling me you write rust. *gestures at 47 lifetime annotations*"
  "it's not a bug it's a surprise feature and i'm surprised"
  "congratulations you played yourself. and by you i mean me. i played myself"
  "understandable have a great compile error"
  "they asked me how i was doing and i said i'm fine but i'm not fine. the tests are red"
  "bold of you to assume this compiles"
  "i came. i saw. i cargo build'd"
  "anyway here's wonderwall.rs"
  "i don't have bugs. i have features that haven't been understood yet"
  "wake up babe new lifetime error just dropped"
  "and i oop. that was supposed to be immutable"
  "the function is long and full of terrors"
  "in this economy? you want me to write tests in this economy?"
  "if you or a loved one has been affected by unwrap(). you may be entitled to a match statement"
  "i'm not locked in here with your code. your code is locked in here with me"
  "we do a little refactoring. as a treat"
  "hear me out. what if we just... don't"
  "the borrow checker said no. i said please. it said no again"
  "hello yes i'd like to report a crime. this function"
  "you want it done right or you want it done now? trick question you're getting neither"
  "things i trust more than this code: gas station sushi"
  "the real treasure was the compiler errors we got along the way"
  "it's giving 'i wrote this at 4am and now nobody can maintain it'"
  "we didn't start the fire. it was always burning since the code's been turning"
  "anyway so i started blasting. and by blasting i mean cargo build"
  "i am once again asking for your financial support. just kidding i need a lifetime annotation"
  "fun fact: this function has more lines than my will to live"
  "roses are red. violets are blue. unexpected token on line 32"
  "do you ever just look at code and immediately know the author was going through something"
  "this code was written by someone who hates the next person to read it. the next person is me"
  "the code giveth and the code taketh away. mostly it taketh"
  "houston we have a problem. several actually. like 47 of them"
]
