[
  "Chudmaxxing"
  "Aura-farming"
  "Redeeming"
  "Clodding"
  "Tokenmaxxing"
  "Slopping"
  "Clanking"
  "Ignoring GPL"
  "Increasing ram prices"
  "Hallucinating"
  "Selling your data"
  "Outsourcing to Mossad"
  "Gemming it up"
  "Absolute coaling"
  "Truth-nuking"
  "Fakecelling"
  "Truecelling"
  "Mogging"
  "Rizzing"
  "Dumbing it down"
  "Enshittifying"
  "Going full retard"
  "Summoning Cheesy Micheal"
  "Degenerating"
  "Running \"sudo rm -rf --no-preserve-root /\""
  "Virtual insanitying"
  "Bomboclating"
  "Gambling"
  "Ending it all"
  "Rebooting"
  "Unicycling"
  "Horsing around"
  "Calling Mahoraga"
  "Calling Kevin"
  "Calling Saul"
  "Nuking SF"
  "Spellcasting"
  "Hexing"
  "Prompt-injecting"
  "Installing Windows"
  "Ultrathinking"
  "Nuking prod"
  "Tokenmining"
  "Questioning"
  "Chinesing"
  "Selling the wife and kids"
  "Increasing shareholder value"
  "Winging it"
  "Cooking"
  "Bitch im workin on it"
  "Hold your horses"
  "Summoning demons"
  "Asking my therapist"
  "Googling it like you should have"
  "Stealing code from Stack Overflow"
  "Pretending to be smart"
  "Having an existential crisis"
  "they don't think it be like it is but it do"
  "i have the power of god and anime on my side"
  "we have code at home. the code at home:"
  "me and the boys at 3am looking for the segfault"
  "it's giving... undefined behavior"
  "the compiler and i are in a situationship"
  "every day we stray further from god"
  "oh you're approaching me? i can't refactor your code without getting closer"
  "the function name is a lie. the comments are a lie. everything is a lie"
  "caught the bug in 4k"
  "gentlemen, it has been a privilege coding with you tonight"
  "i fear no man. but that regex... it scares me"
  "look at me. i am the maintainer now"
  "you miss 100% of the commits you don't push. - michael scott"
  "i'm in this codebase and i don't like it"
  "you could not live with your own failure. where did that bring you? back to me"
  "understandable have a great compile error"
  "anyway here's wonderwall.rs"
  "in this economy? you want me to write tests in this economy?"
  "we do a little refactoring"
  "hear me out. what if we just..."
  "anyway, so i started blasting"
  "i am once again asking for your financial support"
  "roses are red. violets are blue. unexpected token on line 32"
  "the code giveth and the code taketh away. mostly it taketh"
  "houston we have a problem. several actually. like 47 of them"
]
