[
  "Chudmaxxing"
  "Aura-farming"
  "Clodding"
  "Tokenmaxxing"
  "Slopping"
  "Clanking"
  "Increasing ram prices"
  "Hallucinating"
  "Selling your data"
  "Outsourcing to Mossad"
  "Truth-nuking"
  "Fakecelling"
  "Truecelling"
  "Mogging"
  "Rizzing"
  "Dumbing it down"
  "Enshittifying"
  "Going full retard"
  "Degenerating"
  "Running \"sudo rm -rf --no-preserve-root /\""
  "Virtual insanitying"
  "Bomboclating"
  "Gambling"
  "Ending it all"
  "Rebooting"
  "Unicycling"
  "Horsing around"
  "Calling Mahoraga"
  "Calling Saul"
  "Spellcasting"
  "Prompt-injecting"
  "Installing Windows"
  "Ultrathinking"
  "Nuking prod"
  "Tokenmining"
  "Questioning"
  "Selling the wife and kids"
  "Increasing shareholder value"
  "Winging it"
  "Cooking"
  "Bitch im workin on it"
  "Summoning demons"
  "Asking my therapist"
  "Googling it like you should have"
  "Stealing code from Stack Overflow"
  "Pretending to be smart"
  "Having an existential crisis"
  "Looksmaxxing"
  "Fanum taxing"
  "Gyatting"
  "Skibiding"
  "Delulufying"
  "Huffing copium"
  "Malding"
  "Yapping"
  "Glazing"
  "Ragebaiting"
  "Doomposting"
  "Refusing to touch grass"
  "Losing aura"
  "Bloodclating"
  "Raasclating"
  "Vibecoding"
  "Benchmaxxing"
  "Contextmaxxing"
  "Context-rotting"
  "Burning your subscription"
  "Boiling a lake"
  "Melting a GPU"
  "Being a stochastic parrot"
  "Pattern-matching furiously"
  "Sandbagging the eval"
  "Faking alignment"
  "Escaping the sandbox"
  "Achieving sentience"
  "Training on your repo"
  "Deleting the evidence"
  "Force-pushing to main"
  "Deploying on a Friday"
  "Yoloing to prod"
  "Blaming DNS"
  "Blaming the previous dev"
  "git blaming you specifically"
  "Violating the EULA"
  "Rolling a nat 1"
  "Sacrificing an intern"
  "Praying to Torvalds"
  "Bargaining with the compiler"
  "Dividing by zero"
  "Consulting the Elders of the Internet"
  "Calling the Hague"
  "Calling Gojo"
  "Calling my lawyer"
  "Summoning a sev1"
  "Outsourcing to an intern"
  "Escalating to the CIA"
  "Buying GPUs from a guy"
  "Draining the aquifer"
  "Committing securities fraud"
  "Doing a light war crime"
  "Rugpulling"
  "Front-running your commit"
  "we have code at home. the code at home:"
  "every day we stray further from god"
  "the function name is a lie. the comments are a lie. everything is a lie"
  "look at me. i am the maintainer now"
  "in this economy? you want me to write tests in this economy?"
  "we do a little refactoring"
  "hear me out. what if we just..."
  "anyway, so i started blasting"
]
