#!/usr/bin/env python3

from __future__ import annotations

SHORT_CONFIRMATION_MAXIMUM_PROSE_WORDS = 80
REPLY_HARD_WORD_CEILING = 120
LABELED_SECTION_WORD_CEILING = 100
MAXIMUM_LIST_BLOCK_LINES = 5
MAXIMUM_LIST_LINE_WORDS = 20
REQUIRED_REPLY_LABELS = ("What is this session about?", "done", "next")
