#!/usr/bin/env python3

from __future__ import annotations

SHORT_CONFIRMATION_MAXIMUM_PROSE_LINES = 3
SCANNABLE_MAXIMUM_PROSE_LINES = 14
REPLY_TARGET_PROSE_WORDS = 150
REPLY_HARD_WORD_CEILING = 250
REPLY_HARD_CHARACTER_CEILING = 1500
MAXIMUM_PROSE_PARAGRAPH_BLOCKS = 4

ALWAYS_ENFORCED_TIER = "always enforced"
REQUEST_GATED_TIER = "request gated"
