- Watch:
    - Jellyfin:
        icon: jellyfin.png
        href: http://{{HOMEPAGE_VAR_ARR_HOST}}:8096
        description: Stream your movie and TV library
    - Jellyseerr:
        icon: jellyseerr.png
        href: http://{{HOMEPAGE_VAR_ARR_HOST}}:5055
        description: Browse and request new titles

- Management:
    - Radarr:
        icon: radarr.png
        href: http://{{HOMEPAGE_VAR_ARR_HOST}}:7878
        description: Movies
    - Sonarr:
        icon: sonarr.png
        href: http://{{HOMEPAGE_VAR_ARR_HOST}}:8989
        description: TV shows
    - Lidarr:
        icon: lidarr.png
        href: http://{{HOMEPAGE_VAR_ARR_HOST}}:8686
        description: Music
    - Readarr:
        icon: readarr.png
        href: http://{{HOMEPAGE_VAR_ARR_HOST}}:8788
        description: Books
    - Bazarr:
        icon: bazarr.png
        href: http://{{HOMEPAGE_VAR_ARR_HOST}}:6767
        description: Subtitles
    - Prowlarr:
        icon: prowlarr.png
        href: http://{{HOMEPAGE_VAR_ARR_HOST}}:9696
        description: Indexer manager

- Download:
    - qBittorrent:
        icon: qbittorrent.png
        href: http://{{HOMEPAGE_VAR_ARR_HOST}}:8080
        description: Download client
