{
  imports = [
    ./agenix-edit.nix
    ./agenix-edit-phone.nix
    ./claude-exit.nix
    ./daily-note.nix
    ./git-crypt-setup.nix
    ./ksnip-annotate.nix
    ./greatshot-capture.nix
    ./nix-gc.nix
    ./on.nix
    ./pdf-edit.nix
    ./rebuild.nix
    ./set-random-bg-kitty.nix
    ./speed-read.nix
    ./tar-unzip2dir.nix
    ./tmux-lazygit-toggle.nix
    ./tmux-resurrect.nix
    ./volume.nix
  ];
}
