{
  imports = [
    ./agenix-edit.nix
    ./agenix-edit-phone.nix
    ./claude-exit.nix
    ./daily-note.nix
    ./dotfiles-quick-commit.nix
    ./ksnip-annotate.nix
    ./greatshot-capture.nix
    ./git-fzf.nix
    ./nix-gc.nix
    ./on.nix
    ./pdf-edit.nix
    ./rebuild.nix
    ./set-random-bg-kitty.nix
    ./speed-read.nix
    ./tar-unzip2dir.nix
    ./tmux-lazygit-toggle.nix
    ./tmux-btop-toggle.nix
    ./tmux-editor-toggle.nix
    ./tmux-resurrect.nix
    ./brightness.nix
    ./volume.nix
    ./pinchtab.nix
    ./pw.nix
  ];
}
