#!/usr/bin/env bash

IMAGE_DIR="$HOME/.dotfiles/machine-configuration/terminal/emulators/kitty/backgrounds"

RANDOM_IMAGE=$(find "$IMAGE_DIR" -type f | shuf -n 1)

kitty @ set-background-image "$RANDOM_IMAGE"
