set -ogq @thm_bg "{{ background }}"
set -ogq @thm_fg "{{ foreground }}"

set -ogq @thm_rosewater "{{ color15 }}"
set -ogq @thm_flamingo "{{ color1 }}"
set -ogq @thm_pink "{{ color5 }}"
set -ogq @thm_mauve "{{ color5 }}"
set -ogq @thm_red "{{ color1 }}"
set -ogq @thm_maroon "{{ color1 }}"
set -ogq @thm_peach "{{ color3 }}"
set -ogq @thm_yellow "{{ color3 }}"
set -ogq @thm_green "{{ color2 }}"
set -ogq @thm_teal "{{ color6 }}"
set -ogq @thm_sky "{{ color6 }}"
set -ogq @thm_sapphire "{{ color4 }}"
set -ogq @thm_blue "{{ color4 }}"
set -ogq @thm_lavender "{{ color12 }}"

set -ogq @thm_subtext_1 "{{ color15 }}"
set -ogq @thm_subtext_0 "{{ color7 }}"
set -ogq @thm_overlay_2 "{{ color8 }}"
set -ogq @thm_overlay_1 "{{ color8 }}"
set -ogq @thm_overlay_0 "{{ color8 }}"
set -ogq @thm_surface_2 "{{ color8 }}"
set -ogq @thm_surface_1 "{{ color0 }}"
set -ogq @thm_surface_0 "{{ color0 }}"
set -ogq @thm_mantle "{{ background }}"
set -ogq @thm_crust "{{ background }}"
