name: Nix CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, feature*]

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: experimental-features = nix-command flakes

      # - name: Lint (nix fmt --check)
      #   working-directory: nixos
      #   run: nix fmt -- --check .

      - name: Check (nix flake check)
        working-directory: nixos
        run: nix flake check -L --keep-going

      - name: Build NixOS toplevel
        working-directory: nixos
        run: nix build -L .#nixosConfigurations.zanoni.config.system.build.toplevel

      - name: Build Home Manager activationPackage
        working-directory: nixos
        run: nix build -L ".#homeConfigurations.lucas.zanoni@x86_64-linux.activationPackage"
