name: Test run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dotfiles:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        # Install any necessary dependencies here if needed
        sudo apt-get update

    - name: Run install script
      run: |
        yes | sh install.sh

    - name: Test install script
      run: |
        sh test.sh

    - name: Test dotfiles
      run: |
        # TODO: test the configuration of the dotfiles
        # not the installation
        # e.g. test that a alias is working as expected

    - name: Test stow ignore
      run: |
        # TODO: Test that the stow ignore file is working as expected
