name: Test run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dotfiles:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        apt-get update

    - name: Run install script
      run: |
        chmod +x install.sh
        bash
        yes | bash install.sh

    - name: Test install script
      run: |
        # echo $HOME
        # source ~/.bashrc
        # echo $OBSIDIAN_HOME
        chmod +x install.sh
        cat $HOME/.bashrc
        yes | bash install.sh
        bash
        bash test.sh

    # - name: Test dotfiles
    #   run: |
    #     # TODO: Test the configuration of the dotfiles
    #     # not the installation
    #     # e.g. test that an alias is working as expected

    # - name: Test stow ignore
    #   run: |
    #     # TODO: Test that the stow ignore file is working as expected
