name: Test run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dotfiles:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        # Install any necessary dependencies here if needed
        sudo apt-get update

    - name: Run install script
      run: |
        yes | sh install.sh

    - name: Test pkgs
      run: |
        # TODO: Add tests for the installed packages
        # neofetch TODO: its not running because y is not fed to the script
        stow -h

    - name: Test configs
      run: |
        # TODO: Add tests for the installed configs
        # Test that the configs

    - name: Test stow ignore
      run: |
        # TODO: Test that the stow ignore file is working as expected
