name: Test run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dotfiles:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        # Install any necessary dependencies here if needed
        sudo apt-get update

    - name: Run install script
      run: |
        ls -la
        chmod +x install.sh
        sh install.sh
