name: Test run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dotfiles:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        # Install any necessary dependencies
        apt-get update

    - name: Run install script, test install script, and test dotfiles
      run: |
        # TODO: Find a way to run test steps separately
        chmod +x install.sh
        yes | sh install.sh
        sh test.sh

    # Uncomment and adjust these steps when ready
    # - name: Test install script
    #   run: |
    #     sh test.sh

    # - name: Test dotfiles
    #   run: |
    #     # TODO: Test the configuration of the dotfiles
    #     # not the installation
    #     # e.g. test that an alias is working as expected

    # - name: Test stow ignore
    #   run: |
    #     # TODO: Test that the stow ignore file is working as expected
